[versions]
agp = "8.10.0-alpha07"
kotlin = "2.1.0"
coroutines = "1.8.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
media3_version = "1.6.0"
compose_bom = "2025.02.00"
lottie = "6.4.0"
coil = "2.2.2"
ksp = "2.1.0-1.0.29"
activity-compose = "1.10.1"
detekt = "1.23.7"
spotless = "6.25.0"
detekt_compose = "0.4.16+"
jetbrainsKotlinJvm = "2.1.0"
kotlinpoet-ksp = "1.16.0"
datastore = "1.1.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3_version" }
media3-exoplayer-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "media3_version" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3_version" }
media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3_version" }

# Compose Dependencies
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose_bom" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }

detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-cli = { group = "io.gitlab.arturbosch.detekt", name = "detekt-cli", version.ref = "detekt" }
detekt-compose = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detekt_compose" }
ksp-symbol-processing-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet-ksp" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
android-library = { id = "com.android.library", version.ref = "agp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }


[bundles]
androidx-media3 = ["media3-exoplayer", "media3-exoplayer-dash", "media3-ui", "media3-exoplayer-hls"]
androidx-compose = ["compose-runtime", "compose-material3", "compose-ui", "compose-ui-graphics", "compose-ui-tooling", "compose-ui-tooling-preview", "androidx-activity-compose"]
compose-extensions = ["lottie-compose", "coil-compose"]
